/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   auth-mixin.js
 */

declare namespace Fabric {


  /**
   * `Fabric.AuthMixin`
   */
  function AuthMixin<T extends new (...args: any[]) => {}>(base: T): T & AuthMixinConstructor;

  interface AuthMixinConstructor {
    new(...args: any[]): AuthMixin;
  }

  interface AuthMixin {

    /**
     * ign-in provider with pop-up.
     */
    popup: boolean|null|undefined;

    /**
     * Allow Google Sign-in.
     */
    google: boolean|null|undefined;

    /**
     * Allow Facebook Sign-in.
     */
    facebook: boolean|null|undefined;

    /**
     * Allow Twitter Sign-in.
     */
    twitter: boolean|null|undefined;

    /**
     * Allow GitHub Sign-in.
     */
    github: boolean|null|undefined;

    /**
     * Allow Email Sign-in.
     */
    email: boolean|null|undefined;

    /**
     * Allow anonymous Sign-in.
     */
    anonymous: boolean|null|undefined;

    /**
     * Allow phone number Sign-in.
     */
    phone: boolean|null|undefined;

    /**
     * Error
     */
    error: object|null|undefined;

    /**
     * Currently open view.
     */
    selected: string|null|undefined;

    /**
     * Available providers for the given email.
     */
    availableProviders: object|null|undefined;

    /**
     * The minimum length of the input value.
     */
    minLength: number|null|undefined;

    /**
     * Disable email input on sign-up form
     */
    disabled: boolean|null|undefined;

    /**
     * User email
     */
    userEmail: string|null|undefined;

    /**
     * User password
     */
    userPassword: string|null|undefined;

    /**
     * Phone number
     */
    phoneNumber: string|null|undefined;

    /**
     * Phone code
     */
    phoneCode: string|null|undefined;

    /**
     * Confirmation code
     */
    confirmationCode: string|null|undefined;

    /**
     * User object
     */
    user: object|null|undefined;

    /**
     * User is signedIn
     */
    signedIn: boolean|null|undefined;

    /**
     * Country dial codes.
     */
    dialingCodes: any[]|null|undefined;

    /**
     * connectedCallback
     */
    connectedCallback(): void;

    /**
     * Google Sign-in function.
     */
    signInGoogle(): void;

    /**
     * Facebook Sign-in function.
     */
    signInFacebook(): void;

    /**
     * Twitter Sign-in function.
     */
    signInTwitter(): void;

    /**
     * GitHub Sign-in function.
     */
    signInGitHub(): void;

    /**
     * Anonymous Sign-in function.
     */
    signInAnonymously(): void;

    /**
     * Sign In the user.
     */
    _signIn(provider: firebase.auth.AuthProvider|null): void;

    /**
     * Checks if there's any provider for the given email
     */
    fetchEmailProviders(): void;

    /**
     * Sign In with email and password.
     */
    signInWithEmailAndPassword(e: object|null): void;

    /**
     * Password reset.
     */
    passwordReset(): void;

    /**
     * Create user with email and password.
     */
    createUserWithEmailAndPassword(): void;

    /**
     * Sign In with phone number.
     */
    signInWithPhone(): void;

    /**
     * Confirmation code screen.
     */
    showConfirmationCodeScreen(): void;

    /**
     * Sign in the user by passing the code to the confirm method.
     */
    confirmCode(): void;

    /**
     * sign out
     */
    signOut(): firebase.Thenable<any>;

    /**
     * Reset email and password
     */
    clear(): void;
  }
}
