/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   skeleton-auth.js
 *   skeleton-auth.js
 *   skeleton-auth.js
 *   skeleton-auth.js
 *   skeleton-auth.js
 *   skeleton-auth.js
 *   skeleton-auth.js
 *   skeleton-auth.js
 */

/// <reference path="auth-mixin.d.ts" />
/// <reference path="icons.d.ts" />

/**
 * `skeleton-auth`
 *
 * Minimal Sign in module using polymer and firebase
 */
declare class SkeletonAuth extends
  Fabric.AuthMixin(
  Polymer.Element) {

  /**
   * Label Phone Number
   */
  labelPhoneNumber: string|null|undefined;

  /**
   * Label Google
   */
  labelGoogle: string|null|undefined;

  /**
   * Label Facebook
   */
  labelFacebook: string|null|undefined;

  /**
   * Label Twitter
   */
  labelTwitter: string|null|undefined;

  /**
   * Label GitHub
   */
  labelGithub: string|null|undefined;

  /**
   * Label Email
   */
  labelEmail: string|null|undefined;

  /**
   * The label for the email input.
   */
  labelEmailInput: string|null|undefined;

  /**
   * The label for the sign in password input.
   */
  labelPassSignIn: string|null|undefined;

  /**
   * The label for the sign up password input.
   */
  labelPassSignUp: string|null|undefined;

  /**
   * Label labelAnonymous
   */
  labelAnonymous: string|null|undefined;

  /**
   * Label Cancel
   */
  labelCancel: string|null|undefined;

  /**
   * Label Sign Up
   */
  labelSignUp: string|null|undefined;

  /**
   * Label Sign In
   */
  labelSignIn: string|null|undefined;

  /**
   * Label Continue
   */
  labelContinue: string|null|undefined;

  /**
   * Label Send
   */
  labelSend: string|null|undefined;

  /**
   * Label for Forgot Your Password?
   */
  labelForgotPassword: string|null|undefined;

  /**
   * The error message to display when the email input is invalid.
   */
  errorMessageEmail: string|null|undefined;

  /**
   * The error message to display when the password input is invalid.
   */
  errorMessagePass: string|null|undefined;

  /**
   * Headline forgot
   */
  headlineForgot: string|null|undefined;

  /**
   * Headline forgot
   */
  descriptionForgot: string|null|undefined;

  /**
   * Headline
   */
  headlineForgotSent: string|null|undefined;

  /**
   * Headline
   */
  descriptionForgotSent: string|null|undefined;
}

interface HTMLElementTagNameMap {
  "skeleton-auth": SkeletonAuth;
  "skeleton-auth": SkeletonAuth;
  "skeleton-auth": SkeletonAuth;
  "skeleton-auth": SkeletonAuth;
  "skeleton-auth": SkeletonAuth;
  "skeleton-auth": SkeletonAuth;
  "skeleton-auth": SkeletonAuth;
  "skeleton-auth": SkeletonAuth;
}

/**
 * `skeleton-auth`
 *
 * Minimal Sign in module using polymer and firebase
 */
declare class SkeletonAuth extends
  Fabric.AuthMixin(
  Polymer.Element) {

  /**
   * Label Phone Number
   */
  labelPhoneNumber: string|null|undefined;

  /**
   * Label Google
   */
  labelGoogle: string|null|undefined;

  /**
   * Label Facebook
   */
  labelFacebook: string|null|undefined;

  /**
   * Label Twitter
   */
  labelTwitter: string|null|undefined;

  /**
   * Label GitHub
   */
  labelGithub: string|null|undefined;

  /**
   * Label Email
   */
  labelEmail: string|null|undefined;

  /**
   * The label for the email input.
   */
  labelEmailInput: string|null|undefined;

  /**
   * The label for the sign in password input.
   */
  labelPassSignIn: string|null|undefined;

  /**
   * The label for the sign up password input.
   */
  labelPassSignUp: string|null|undefined;

  /**
   * Label labelAnonymous
   */
  labelAnonymous: string|null|undefined;

  /**
   * Label Cancel
   */
  labelCancel: string|null|undefined;

  /**
   * Label Sign Up
   */
  labelSignUp: string|null|undefined;

  /**
   * Label Sign In
   */
  labelSignIn: string|null|undefined;

  /**
   * Label Continue
   */
  labelContinue: string|null|undefined;

  /**
   * Label Send
   */
  labelSend: string|null|undefined;

  /**
   * Label for Forgot Your Password?
   */
  labelForgotPassword: string|null|undefined;

  /**
   * The error message to display when the email input is invalid.
   */
  errorMessageEmail: string|null|undefined;

  /**
   * The error message to display when the password input is invalid.
   */
  errorMessagePass: string|null|undefined;

  /**
   * Headline forgot
   */
  headlineForgot: string|null|undefined;

  /**
   * Headline forgot
   */
  descriptionForgot: string|null|undefined;

  /**
   * Headline
   */
  headlineForgotSent: string|null|undefined;

  /**
   * Headline
   */
  descriptionForgotSent: string|null|undefined;
}

/**
 * `skeleton-auth`
 *
 * Minimal Sign in module using polymer and firebase
 */
declare class SkeletonAuth extends
  Fabric.AuthMixin(
  Polymer.Element) {

  /**
   * Label Phone Number
   */
  labelPhoneNumber: string|null|undefined;

  /**
   * Label Google
   */
  labelGoogle: string|null|undefined;

  /**
   * Label Facebook
   */
  labelFacebook: string|null|undefined;

  /**
   * Label Twitter
   */
  labelTwitter: string|null|undefined;

  /**
   * Label GitHub
   */
  labelGithub: string|null|undefined;

  /**
   * Label Email
   */
  labelEmail: string|null|undefined;

  /**
   * The label for the email input.
   */
  labelEmailInput: string|null|undefined;

  /**
   * The label for the sign in password input.
   */
  labelPassSignIn: string|null|undefined;

  /**
   * The label for the sign up password input.
   */
  labelPassSignUp: string|null|undefined;

  /**
   * Label labelAnonymous
   */
  labelAnonymous: string|null|undefined;

  /**
   * Label Cancel
   */
  labelCancel: string|null|undefined;

  /**
   * Label Sign Up
   */
  labelSignUp: string|null|undefined;

  /**
   * Label Sign In
   */
  labelSignIn: string|null|undefined;

  /**
   * Label Continue
   */
  labelContinue: string|null|undefined;

  /**
   * Label Send
   */
  labelSend: string|null|undefined;

  /**
   * Label for Forgot Your Password?
   */
  labelForgotPassword: string|null|undefined;

  /**
   * The error message to display when the email input is invalid.
   */
  errorMessageEmail: string|null|undefined;

  /**
   * The error message to display when the password input is invalid.
   */
  errorMessagePass: string|null|undefined;

  /**
   * Headline forgot
   */
  headlineForgot: string|null|undefined;

  /**
   * Headline forgot
   */
  descriptionForgot: string|null|undefined;

  /**
   * Headline
   */
  headlineForgotSent: string|null|undefined;

  /**
   * Headline
   */
  descriptionForgotSent: string|null|undefined;
}

/**
 * `skeleton-auth`
 *
 * Minimal Sign in module using polymer and firebase
 */
declare class SkeletonAuth extends
  Fabric.AuthMixin(
  Polymer.Element) {

  /**
   * Label Phone Number
   */
  labelPhoneNumber: string|null|undefined;

  /**
   * Label Google
   */
  labelGoogle: string|null|undefined;

  /**
   * Label Facebook
   */
  labelFacebook: string|null|undefined;

  /**
   * Label Twitter
   */
  labelTwitter: string|null|undefined;

  /**
   * Label GitHub
   */
  labelGithub: string|null|undefined;

  /**
   * Label Email
   */
  labelEmail: string|null|undefined;

  /**
   * The label for the email input.
   */
  labelEmailInput: string|null|undefined;

  /**
   * The label for the sign in password input.
   */
  labelPassSignIn: string|null|undefined;

  /**
   * The label for the sign up password input.
   */
  labelPassSignUp: string|null|undefined;

  /**
   * Label labelAnonymous
   */
  labelAnonymous: string|null|undefined;

  /**
   * Label Cancel
   */
  labelCancel: string|null|undefined;

  /**
   * Label Sign Up
   */
  labelSignUp: string|null|undefined;

  /**
   * Label Sign In
   */
  labelSignIn: string|null|undefined;

  /**
   * Label Continue
   */
  labelContinue: string|null|undefined;

  /**
   * Label Send
   */
  labelSend: string|null|undefined;

  /**
   * Label for Forgot Your Password?
   */
  labelForgotPassword: string|null|undefined;

  /**
   * The error message to display when the email input is invalid.
   */
  errorMessageEmail: string|null|undefined;

  /**
   * The error message to display when the password input is invalid.
   */
  errorMessagePass: string|null|undefined;

  /**
   * Headline forgot
   */
  headlineForgot: string|null|undefined;

  /**
   * Headline forgot
   */
  descriptionForgot: string|null|undefined;

  /**
   * Headline
   */
  headlineForgotSent: string|null|undefined;

  /**
   * Headline
   */
  descriptionForgotSent: string|null|undefined;
}

/**
 * `skeleton-auth`
 *
 * Minimal Sign in module using polymer and firebase
 */
declare class SkeletonAuth extends
  Fabric.AuthMixin(
  Polymer.Element) {

  /**
   * Label Phone Number
   */
  labelPhoneNumber: string|null|undefined;

  /**
   * Label Google
   */
  labelGoogle: string|null|undefined;

  /**
   * Label Facebook
   */
  labelFacebook: string|null|undefined;

  /**
   * Label Twitter
   */
  labelTwitter: string|null|undefined;

  /**
   * Label GitHub
   */
  labelGithub: string|null|undefined;

  /**
   * Label Email
   */
  labelEmail: string|null|undefined;

  /**
   * The label for the email input.
   */
  labelEmailInput: string|null|undefined;

  /**
   * The label for the sign in password input.
   */
  labelPassSignIn: string|null|undefined;

  /**
   * The label for the sign up password input.
   */
  labelPassSignUp: string|null|undefined;

  /**
   * Label labelAnonymous
   */
  labelAnonymous: string|null|undefined;

  /**
   * Label Cancel
   */
  labelCancel: string|null|undefined;

  /**
   * Label Sign Up
   */
  labelSignUp: string|null|undefined;

  /**
   * Label Sign In
   */
  labelSignIn: string|null|undefined;

  /**
   * Label Continue
   */
  labelContinue: string|null|undefined;

  /**
   * Label Send
   */
  labelSend: string|null|undefined;

  /**
   * Label for Forgot Your Password?
   */
  labelForgotPassword: string|null|undefined;

  /**
   * The error message to display when the email input is invalid.
   */
  errorMessageEmail: string|null|undefined;

  /**
   * The error message to display when the password input is invalid.
   */
  errorMessagePass: string|null|undefined;

  /**
   * Headline forgot
   */
  headlineForgot: string|null|undefined;

  /**
   * Headline forgot
   */
  descriptionForgot: string|null|undefined;

  /**
   * Headline
   */
  headlineForgotSent: string|null|undefined;

  /**
   * Headline
   */
  descriptionForgotSent: string|null|undefined;
}

/**
 * `skeleton-auth`
 *
 * Minimal Sign in module using polymer and firebase
 */
declare class SkeletonAuth extends
  Fabric.AuthMixin(
  Polymer.Element) {

  /**
   * Label Phone Number
   */
  labelPhoneNumber: string|null|undefined;

  /**
   * Label Google
   */
  labelGoogle: string|null|undefined;

  /**
   * Label Facebook
   */
  labelFacebook: string|null|undefined;

  /**
   * Label Twitter
   */
  labelTwitter: string|null|undefined;

  /**
   * Label GitHub
   */
  labelGithub: string|null|undefined;

  /**
   * Label Email
   */
  labelEmail: string|null|undefined;

  /**
   * The label for the email input.
   */
  labelEmailInput: string|null|undefined;

  /**
   * The label for the sign in password input.
   */
  labelPassSignIn: string|null|undefined;

  /**
   * The label for the sign up password input.
   */
  labelPassSignUp: string|null|undefined;

  /**
   * Label labelAnonymous
   */
  labelAnonymous: string|null|undefined;

  /**
   * Label Cancel
   */
  labelCancel: string|null|undefined;

  /**
   * Label Sign Up
   */
  labelSignUp: string|null|undefined;

  /**
   * Label Sign In
   */
  labelSignIn: string|null|undefined;

  /**
   * Label Continue
   */
  labelContinue: string|null|undefined;

  /**
   * Label Send
   */
  labelSend: string|null|undefined;

  /**
   * Label for Forgot Your Password?
   */
  labelForgotPassword: string|null|undefined;

  /**
   * The error message to display when the email input is invalid.
   */
  errorMessageEmail: string|null|undefined;

  /**
   * The error message to display when the password input is invalid.
   */
  errorMessagePass: string|null|undefined;

  /**
   * Headline forgot
   */
  headlineForgot: string|null|undefined;

  /**
   * Headline forgot
   */
  descriptionForgot: string|null|undefined;

  /**
   * Headline
   */
  headlineForgotSent: string|null|undefined;

  /**
   * Headline
   */
  descriptionForgotSent: string|null|undefined;
}

/**
 * `skeleton-auth`
 *
 * Minimal Sign in module using polymer and firebase
 */
declare class SkeletonAuth extends
  Fabric.AuthMixin(
  Polymer.Element) {

  /**
   * Label Phone Number
   */
  labelPhoneNumber: string|null|undefined;

  /**
   * Label Google
   */
  labelGoogle: string|null|undefined;

  /**
   * Label Facebook
   */
  labelFacebook: string|null|undefined;

  /**
   * Label Twitter
   */
  labelTwitter: string|null|undefined;

  /**
   * Label GitHub
   */
  labelGithub: string|null|undefined;

  /**
   * Label Email
   */
  labelEmail: string|null|undefined;

  /**
   * The label for the email input.
   */
  labelEmailInput: string|null|undefined;

  /**
   * The label for the sign in password input.
   */
  labelPassSignIn: string|null|undefined;

  /**
   * The label for the sign up password input.
   */
  labelPassSignUp: string|null|undefined;

  /**
   * Label labelAnonymous
   */
  labelAnonymous: string|null|undefined;

  /**
   * Label Cancel
   */
  labelCancel: string|null|undefined;

  /**
   * Label Sign Up
   */
  labelSignUp: string|null|undefined;

  /**
   * Label Sign In
   */
  labelSignIn: string|null|undefined;

  /**
   * Label Continue
   */
  labelContinue: string|null|undefined;

  /**
   * Label Send
   */
  labelSend: string|null|undefined;

  /**
   * Label for Forgot Your Password?
   */
  labelForgotPassword: string|null|undefined;

  /**
   * The error message to display when the email input is invalid.
   */
  errorMessageEmail: string|null|undefined;

  /**
   * The error message to display when the password input is invalid.
   */
  errorMessagePass: string|null|undefined;

  /**
   * Headline forgot
   */
  headlineForgot: string|null|undefined;

  /**
   * Headline forgot
   */
  descriptionForgot: string|null|undefined;

  /**
   * Headline
   */
  headlineForgotSent: string|null|undefined;

  /**
   * Headline
   */
  descriptionForgotSent: string|null|undefined;
}

/**
 * `skeleton-auth`
 *
 * Minimal Sign in module using polymer and firebase
 */
declare class SkeletonAuth extends
  Fabric.AuthMixin(
  Polymer.Element) {

  /**
   * Label Phone Number
   */
  labelPhoneNumber: string|null|undefined;

  /**
   * Label Google
   */
  labelGoogle: string|null|undefined;

  /**
   * Label Facebook
   */
  labelFacebook: string|null|undefined;

  /**
   * Label Twitter
   */
  labelTwitter: string|null|undefined;

  /**
   * Label GitHub
   */
  labelGithub: string|null|undefined;

  /**
   * Label Email
   */
  labelEmail: string|null|undefined;

  /**
   * The label for the email input.
   */
  labelEmailInput: string|null|undefined;

  /**
   * The label for the sign in password input.
   */
  labelPassSignIn: string|null|undefined;

  /**
   * The label for the sign up password input.
   */
  labelPassSignUp: string|null|undefined;

  /**
   * Label labelAnonymous
   */
  labelAnonymous: string|null|undefined;

  /**
   * Label Cancel
   */
  labelCancel: string|null|undefined;

  /**
   * Label Sign Up
   */
  labelSignUp: string|null|undefined;

  /**
   * Label Sign In
   */
  labelSignIn: string|null|undefined;

  /**
   * Label Continue
   */
  labelContinue: string|null|undefined;

  /**
   * Label Send
   */
  labelSend: string|null|undefined;

  /**
   * Label for Forgot Your Password?
   */
  labelForgotPassword: string|null|undefined;

  /**
   * The error message to display when the email input is invalid.
   */
  errorMessageEmail: string|null|undefined;

  /**
   * The error message to display when the password input is invalid.
   */
  errorMessagePass: string|null|undefined;

  /**
   * Headline forgot
   */
  headlineForgot: string|null|undefined;

  /**
   * Headline forgot
   */
  descriptionForgot: string|null|undefined;

  /**
   * Headline
   */
  headlineForgotSent: string|null|undefined;

  /**
   * Headline
   */
  descriptionForgotSent: string|null|undefined;
}
